### PR TITLE
Commas (and other puctuation) should come after the arrow icon of external links

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Comment by ignasi35** [comment]
Screenshot 2020-10-05 at 16 46 09

**Comment by ignasi35** [comment]
Hi @rstento, what do you think of this improvement?

**Comment by rstento** [comment]
@ignasi35, I actually did it this way because visually I thought that punctuation separates the arrow from the link. I guess it's subjective.

**Comment by ignasi35** [comment]
> @ignasi35, I actually did it this way because visually I thought that punctuation separates the arrow from the link. 

The problem with that approach is on sentences where there's a list of external links separated by commas:

```
Higher-level representations of this aspect are https://grpc.io/[gRPC], https://grpc.io/[{tab}, window="new tab"] https://nats.io/[NATS.io], https://nats.io/[{tab}, window="new tab"] https://kafka.apache.org/[Apache Kafka], https://kafka.apache.org/[{tab}, window="new tab"] HTTP & REST 
```

Putting the icon after comma is miss-leading because the first arrow is closer to the second link. The final approach in akka-platform-guide was to add the arrow in the [same asciidoc element](https://github.com/akka/akka-platform-guide/blob/1a7e56d2c9558ae9fd899a422915eaf943e0f861/docs-source/docs/modules/concepts/pages/akka-management.adoc#L18):

```
{akka-management}/bootstrap/index.html[Bootstrap {tab-icon}, window="tab"] 
```

When doing that there's no possible confusion.

> I also would make all external links go to a new tab/window instead of having the link do one thing and the icon do another.

Yep, I agree that's the best choice.

**Pull request merged**
